language: node_js
cache:
  directories:
    - node_modules
notifications:
  slack: dadi:pnhiL60xOrm7GOglHUmb7xHK
  email: false
node_js:
  - '6'
  - '10'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
services:
  - mongodb
  - redis-server
before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@latest; fi
